apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: eg-experiment
spec:
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: blcox/dtc-model:v11.0
                name: dtc-model
              - image: blcox/gbc-model:v11.0
                name: gbc-model
              - image: seldonio/mab_epsilon_greedy:1.6.0-dev
                name: eg-router
      graph:
        children:
          - name: dtc-model
            type: MODEL
          - name: gbc-model
            type: MODEL
        name: eg-router
        parameters:
          - name: n_branches
            type: INT
            value: '2'
          - name: epsilon
            type: FLOAT
            value: '0.1'
          - name: verbose
            type: BOOL
            value: '1'
          - name: branch_names
            type: STRING
            value: dtc:gbc
          - name: seed
            type: INT
            value: '1'
        type: ROUTER
      name: eg-2
      replicas: 1
      svcOrchSpec:
        env:
          - name: SELDON_ENABLE_ROUTING_INJECTION
            value: 'true'
